DROP INDEX IF EXISTS idx_pomodoro_user;
DROP TABLE IF EXISTS pomodoro_sessions;
DROP TABLE IF EXISTS task_share_tokens;
DROP TABLE IF EXISTS outbound_webhooks;
DROP TABLE IF EXISTS github_task_links;
ALTER TABLE users DROP COLUMN IF EXISTS totp_enabled;
DROP TABLE IF EXISTS totp_secrets;
DROP TABLE IF EXISTS api_tokens;
DROP TABLE IF EXISTS saved_filters;
DROP TABLE IF EXISTS task_watchers;
DROP TABLE IF EXISTS custom_field_values;
DROP TABLE IF EXISTS custom_field_definitions;
DROP TABLE IF EXISTS task_templates;
DROP TABLE IF EXISTS sprint_tasks;
DROP TABLE IF EXISTS sprints;
DROP INDEX IF EXISTS idx_time_entries_user;
DROP INDEX IF EXISTS idx_time_entries_task;
DROP TABLE IF EXISTS time_entries;
ALTER TABLE tasks DROP COLUMN IF EXISTS project_id;
DROP TABLE IF EXISTS projects;
ALTER TABLE tasks DROP COLUMN IF EXISTS effort_points;
